/*
 * test_decompile.c
 * Simple test to output decompiled C code
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "src/e9patch/analysis/e9studio_analysis.h"

#define BUF_SIZE (64 * 1024)

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <binary.elf> [function_name]\n", argv[0]);
        return 1;
    }

    const char *binary_path = argv[1];
    const char *func_name = argc > 2 ? argv[2] : NULL;

    /* Initialize analysis engine */
    if (e9studio_analysis_init() < 0) {
        fprintf(stderr, "Failed to initialize analysis engine\n");
        return 1;
    }

    /* Load binary */
    if (e9studio_load_binary(binary_path) < 0) {
        fprintf(stderr, "Failed to load binary: %s\n", binary_path);
        e9studio_analysis_shutdown();
        return 1;
    }

    printf("/* Decompiled from: %s */\n", binary_path);
    printf("/* Generated by E9Studio */\n\n");
    printf("#include <cosmopolitan.h>\n\n");

    /* Get decompiled output */
    char *buf = malloc(BUF_SIZE);
    if (!buf) {
        fprintf(stderr, "Memory allocation failed\n");
        e9studio_analysis_shutdown();
        return 1;
    }

    const char *result = e9studio_get_decompiled(func_name, buf, BUF_SIZE);
    if (result) {
        printf("%s\n", result);
    } else {
        printf("/* No decompilation available */\n");
    }

    free(buf);
    e9studio_analysis_shutdown();
    return 0;
}

